# This file is part of breaks.
# https://github.com/fitnr/breaks

# Licensed under the GPL license:
# https://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016, Neil Freeman <contact@fakeisthenewreal.org>

language: python

python:
    - 2.7
    - 3.3
    - 3.5

os:
 - linux

before_install:
    - gcc --version
    - pip install -U pip docutils coverage
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew list gdal || brew install gdal; fi
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew list scipy || brew install scipy --with-openblas; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q update; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q install -y libgdal1-dev libblas-dev liblapack-dev gfortran; fi
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get -q install -y python-numpy python-scipy; fi

install:
    - python setup.py install

script:
    - make test
    - make bins.shp
    - make bins.json

after_script:
    - grep bins bins.json > /dev/null && echo bins
