# This file is part of breaks.
# https://github.com/fitnr/breaks

# Licensed under the GPL license:
# https://opensource.org/licenses/GPL-3.0
# Copyright (c) 2016, fitnr <contact@fakeisthenewreal.org>

language: python

python:
    - 2.7
    - 3.3
    - 3.4

install:
    - python setup.py install
    - pip install coverage

script:
    - make test
